### ISSUE TITLE
Build fails - $ and ; expected?

### ISSUE THREAD

**Issue by ThisGuyNeedsABeer** [Dec0ne/KrbRelayUp#8]
Am I being naive to think that there are missing ";" and random "$" placed throughout on purpose to prevent compilation? I would very much like to audit my internal domain so we can ensure when we do enable LDAP signing and the other various restrictions to prevent users from adding a machine to the domain that our mitigations, did in fact work.

VSCode is error after error in almost every ".cs" file.

**Comment by Dec0ne** [comment]
I think you might have an old version of c# that does not support string interpolation using $ and you should update it in order to compile KrbRelayUp. This feature of string interpolation using $ was introduced in c# version 6.

For reference:
https://stackoverflow.com/questions/31014869/what-does-mean-before-a-string

**Comment by ThisGuyNeedsABeer** [comment]
I updated to Visual Studio Community 2022, latest versions, and built successfully. I feel like a complete idiot. Thank you!

**Comment by Dec0ne** [comment]
No worries :)
